_wandb:
    value:
        cli_version: 0.26.1
        e:
            p71xznn4p0d8ko08y5bidwm5bu19ntcm:
                apple:
                    ecpuCores: 2
                    gpuCores: 14
                    macModel: MacBookPro18,3
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "4294967296"
                codePath: 4.rd/1.IAChronicleDetector/0.IAChronicleDetection/5.MachineLearningAudio-PretrainedModel/train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "467315163136"
                email: eglantine.fonrose@uphf.fr
                executable: /Users/eglantine/Dev/0.perso/2.Proutechos/9.GroovyMorning/4.rd/1.IAChronicleDetector/0.IAChronicleDetection/5.MachineLearningAudio-PretrainedModel/.venv/bin/python
                git:
                    commit: 906d70f1dd0e82ed3aa39a133d8d1171b4bdbb0e
                    remote: https://github.com/eglantinefonrose/GroovyMorning_RLAC.git
                host: MacBook-Pro-6.local
                memory:
                    total: "17179869184"
                os: macOS-15.3.1-arm64-arm-64bit
                program: /Users/eglantine/Dev/0.perso/2.Proutechos/9.GroovyMorning/4.rd/1.IAChronicleDetector/0.IAChronicleDetection/5.MachineLearningAudio-PretrainedModel/train.py
                python: CPython 3.12.2
                root: /Users/eglantine/Dev/0.perso/2.Proutechos/9.GroovyMorning/4.rd/1.IAChronicleDetector/0.IAChronicleDetection/5.MachineLearningAudio-PretrainedModel
                startedAt: "2026-05-03T13:03:28.092665Z"
                writerId: p71xznn4p0d8ko08y5bidwm5bu19ntcm
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 100
            "3":
                - 13
            "4": 3.12.2
            "5": 0.26.1
            "6": 5.7.0
            "12": 0.26.1
            "13": darwin-arm64
