_name_or_path:
    value: facebook/wav2vec2-large-xlsr-53-french
_wandb:
    value:
        cli_version: 0.26.1
        e:
            k8q59fzwwsr2cssjv92il7nc0s61l6u3:
                apple:
                    ecpuCores: 2
                    gpuCores: 14
                    macModel: MacBookPro18,3
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "5368709120"
                codePath: 4.rd/1.IAChronicleDetector/0.IAChronicleDetection/5.MachineLearningAudio-PretrainedModel/train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "473413873664"
                email: eglantine.fonrose@uphf.fr
                executable: /Users/eglantine/Dev/0.perso/2.Proutechos/9.GroovyMorning/4.rd/1.IAChronicleDetector/0.IAChronicleDetection/5.MachineLearningAudio-PretrainedModel/.venv/bin/python
                git:
                    commit: d925a9496fa89b9e3779301614f4978451ec0076
                    remote: https://github.com/eglantinefonrose/GroovyMorning_RLAC.git
                host: MacBook-Pro-6.local
                memory:
                    total: "17179869184"
                os: macOS-15.3.1-arm64-arm-64bit
                program: /Users/eglantine/Dev/0.perso/2.Proutechos/9.GroovyMorning/4.rd/1.IAChronicleDetector/0.IAChronicleDetection/5.MachineLearningAudio-PretrainedModel/train.py
                python: CPython 3.12.2
                root: /Users/eglantine/Dev/0.perso/2.Proutechos/9.GroovyMorning/4.rd/1.IAChronicleDetector/0.IAChronicleDetection/5.MachineLearningAudio-PretrainedModel
                startedAt: "2026-05-03T13:38:46.093230Z"
                writerId: k8q59fzwwsr2cssjv92il7nc0s61l6u3
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 100
            "3":
                - 7
                - 13
                - 19
                - 66
            "4": 3.12.2
            "5": 0.26.1
            "6": 5.7.0
            "9":
                "1": transformers_trainer
            "12": 0.26.1
            "13": darwin-arm64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation_dropout:
    value: 0.1
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
adapter_attn_dim:
    value: null
adapter_kernel_size:
    value: 3
adapter_stride:
    value: 2
add_adapter:
    value: false
apply_spec_augment:
    value: true
architectures:
    value:
        - Wav2Vec2ForCTC
attention_dropout:
    value: 0.1
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
batch_eval_metrics:
    value: false
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: 1
chunk_size_feed_forward:
    value: 0
classifier_proj_size:
    value: 256
codevector_dim:
    value: 256
contrastive_logits_temperature:
    value: 0.1
conv_bias:
    value: true
conv_dim:
    value:
        - 512
        - 512
        - 512
        - 512
        - 512
        - 512
        - 512
conv_kernel:
    value:
        - 10
        - 3
        - 3
        - 3
        - 3
        - 2
        - 2
conv_stride:
    value:
        - 5
        - 2
        - 2
        - 2
        - 2
        - 2
        - 2
ctc_loss_reduction:
    value: sum
ctc_zero_infinity:
    value: false
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_static_graph:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_loss_weight:
    value: 0.1
do_eval:
    value: true
do_predict:
    value: false
do_stable_layer_norm:
    value: true
do_train:
    value: false
dtype:
    value: float32
enable_jit_checkpoint:
    value: false
eos_token_id:
    value: 2
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: epoch
eval_use_gather_object:
    value: false
feat_extract_activation:
    value: gelu
feat_extract_dropout:
    value: 0
feat_extract_norm:
    value: layer
feat_proj_dropout:
    value: 0.1
feat_quantizer_dropout:
    value: 0
final_dropout:
    value: 0.1
fp16:
    value: false
fp16_full_eval:
    value: false
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: true
hidden_act:
    value: gelu
hidden_dropout:
    value: 0.1
hidden_dropout_prob:
    value: 0.1
hidden_size:
    value: 1024
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": 8h30-franceinfo
        "1": RTL-évenement
        "2": angle-eco
        "3": angle_eco
        "4": avec-sciences
        "5": bientot-chez-vous
        "6": c-est-notre-epoque
        "7": c_est_notre_epoque
        "8": ca-va-beaucoup-mieux
        "9": ca-va-mieux
        "10": ca_va_beaucoup_mieux
        "11": comme-personne
        "12": dans-l-oeil-de
        "13": dans-la-bouche-de-sophia-aram
        "14": edito-etienne-gernelle
        "15": edito_etienne
        "16": face-a-fogiel
        "17": face_a_fogiel
        "18": franceinfo-monde
        "19": geopolitique
        "20": grand-reportage
        "21": invite-7h40
        "22": invite-RTL-7h40
        "23": invite_7h40
        "24": jimmy-mohamed
        "25": journal-7h
        "26": journal-8h
        "27": journal-9h
        "28": journal-de-7-h
        "29": journal-de-8-h
        "30": journal-de-8h
        "31": journal_7h
        "32": journal_8h
        "33": journal_9h
        "34": l-angle-eco
        "35": l-edito-eco
        "36": l-edito-medias
        "37": l-edito-politique
        "38": l-humeur-du-matin-par-guillaume-erner
        "39": l-invite-de-7h50
        "40": l-invite-de-8h20-le-grand-entretien
        "41": l-invite-de-rtl
        "42": l-invite-e-des-matins
        "43": l-oeil-d-alex-vizorek
        "44": l-oeil-de-constance
        "45": l-oeil-de-julie
        "46": la-chronique-de-tristan-lopin
        "47": la-meteo
        "48": la-pepite
        "49": la-question-de-david-castello-lopes
        "50": la-revue-de-presse-internationale
        "51": la_pepite
        "52": laurent-gerra
        "53": laurent_gerra
        "54": le-billet-de-bertrand-chameroy
        "55": le-billet-de-mosimann
        "56": le-billet-politique
        "57": le-brief-eco
        "58": le-choix-de-franceinfo
        "59": le-decryptage-eco
        "60": le-grand-reportage-de-france-inter
        "61": le-journal-de-6h00
        "62": le-journal-de-7h00
        "63": le-journal-de-8h
        "64": le-journal-de-8h00
        "65": le-journal-de-l-eco
        "66": le-monde-en-marche
        "67": le-regard-culturel
        "68": le-reportage-de-la-redaction
        "69": le-visage-du-jour
        "70": le-vrai-du-faux
        "71": le-vrai-ou-faux
        "72": les-80
        "73": les-chantiers-de-la-recherche
        "74": les-enjeux-internationaux
        "75": merci-vero
        "76": meteo
        "77": meteo-7-jours
        "78": meteo-7h30
        "79": meteo_a_7_jours
        "80": monde-en-marche
        "81": monde_en_marche
        "82": musicaline
        "83": oeil-phillipe
        "84": oeil_philippe
        "85": olivier-dauvers
        "86": olivier_dauvers
        "87": oliviers-devaurs
        "88": question-internationale
        "89": question-internationelle
        "90": question_internationale
        "91": rtl-evenement
        "92": rtl_evenement
        "93": un-monde-connecte
        "94": un-monde-nouveau
        "95": va-savoir
        "96": visage-du-jour
        "97": visage_du_jour
        "98": vrai-du-faux
        "99": vrai_du_faux
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_num_input_tokens_seen:
    value: "no"
initializer_range:
    value: 0.02
intermediate_size:
    value: 4096
is_encoder_decoder:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        8h30-franceinfo: 0
        RTL-évenement: 1
        angle-eco: 2
        angle_eco: 3
        avec-sciences: 4
        bientot-chez-vous: 5
        c-est-notre-epoque: 6
        c_est_notre_epoque: 7
        ca-va-beaucoup-mieux: 8
        ca-va-mieux: 9
        ca_va_beaucoup_mieux: 10
        comme-personne: 11
        dans-l-oeil-de: 12
        dans-la-bouche-de-sophia-aram: 13
        edito-etienne-gernelle: 14
        edito_etienne: 15
        face-a-fogiel: 16
        face_a_fogiel: 17
        franceinfo-monde: 18
        geopolitique: 19
        grand-reportage: 20
        invite-7h40: 21
        invite-RTL-7h40: 22
        invite_7h40: 23
        jimmy-mohamed: 24
        journal-7h: 25
        journal-8h: 26
        journal-9h: 27
        journal-de-7-h: 28
        journal-de-8h: 30
        journal-de-8-h: 29
        journal_7h: 31
        journal_8h: 32
        journal_9h: 33
        l-angle-eco: 34
        l-edito-eco: 35
        l-edito-medias: 36
        l-edito-politique: 37
        l-humeur-du-matin-par-guillaume-erner: 38
        l-invite-de-7h50: 39
        l-invite-de-8h20-le-grand-entretien: 40
        l-invite-de-rtl: 41
        l-invite-e-des-matins: 42
        l-oeil-d-alex-vizorek: 43
        l-oeil-de-constance: 44
        l-oeil-de-julie: 45
        la-chronique-de-tristan-lopin: 46
        la-meteo: 47
        la-pepite: 48
        la-question-de-david-castello-lopes: 49
        la-revue-de-presse-internationale: 50
        la_pepite: 51
        laurent-gerra: 52
        laurent_gerra: 53
        le-billet-de-bertrand-chameroy: 54
        le-billet-de-mosimann: 55
        le-billet-politique: 56
        le-brief-eco: 57
        le-choix-de-franceinfo: 58
        le-decryptage-eco: 59
        le-grand-reportage-de-france-inter: 60
        le-journal-de-6h00: 61
        le-journal-de-7h00: 62
        le-journal-de-8h: 63
        le-journal-de-8h00: 64
        le-journal-de-l-eco: 65
        le-monde-en-marche: 66
        le-regard-culturel: 67
        le-reportage-de-la-redaction: 68
        le-visage-du-jour: 69
        le-vrai-du-faux: 70
        le-vrai-ou-faux: 71
        les-80: 72
        les-chantiers-de-la-recherche: 73
        les-enjeux-internationaux: 74
        merci-vero: 75
        meteo: 76
        meteo-7h30: 78
        meteo-7-jours: 77
        meteo_a_7_jours: 79
        monde-en-marche: 80
        monde_en_marche: 81
        musicaline: 82
        oeil-phillipe: 83
        oeil_philippe: 84
        olivier-dauvers: 85
        olivier_dauvers: 86
        oliviers-devaurs: 87
        question-internationale: 88
        question-internationelle: 89
        question_internationale: 90
        rtl-evenement: 91
        rtl_evenement: 92
        un-monde-connecte: 93
        un-monde-nouveau: 94
        va-savoir: 95
        visage-du-jour: 96
        visage_du_jour: 97
        vrai-du-faux: 98
        vrai_du_faux: 99
layer_norm_eps:
    value: 1e-05
layerdrop:
    value: 0.1
learning_rate:
    value: 3e-05
length_column_name:
    value: length
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: true
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: null
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: linear
mask_feature_length:
    value: 10
mask_feature_min_masks:
    value: 0
mask_feature_prob:
    value: 0
mask_time_length:
    value: 10
mask_time_min_masks:
    value: 2
mask_time_prob:
    value: 0.05
max_grad_norm:
    value: 1
max_steps:
    value: -1
metric_for_best_model:
    value: accuracy
model/num_parameters:
    value: 315726820
model_type:
    value: wav2vec2
neftune_noise_alpha:
    value: null
num_adapter_layers:
    value: 3
num_attention_heads:
    value: 16
num_codevector_groups:
    value: 2
num_codevectors_per_group:
    value: 320
num_conv_pos_embedding_groups:
    value: 16
num_conv_pos_embeddings:
    value: 128
num_feat_extract_layers:
    value: 7
num_hidden_layers:
    value: 24
num_negatives:
    value: 100
num_train_epochs:
    value: 5
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./model_output
output_hidden_size:
    value: 1024
output_hidden_states:
    value: false
pad_token_id:
    value: 0
parallelism_config:
    value: null
per_device_eval_batch_size:
    value: 4
per_device_train_batch_size:
    value: 4
prediction_loss_only:
    value: false
problem_type:
    value: null
proj_codevector_dim:
    value: 256
project:
    value: huggingface
push_to_hub:
    value: false
remove_unused_columns:
    value: true
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
run_name:
    value: null
save_on_each_node:
    value: false
save_only_model:
    value: false
save_steps:
    value: 500
save_strategy:
    value: epoch
save_total_limit:
    value: null
seed:
    value: 42
skip_memory_metrics:
    value: true
tdnn_dilation:
    value:
        - 1
        - 2
        - 3
        - 1
        - 1
tdnn_dim:
    value:
        - 512
        - 512
        - 512
        - 512
        - 1500
tdnn_kernel:
    value:
        - 5
        - 3
        - 3
        - 1
        - 1
tf32:
    value: null
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
trackio_bucket_id:
    value: null
trackio_space_id:
    value: null
trackio_static_space_id:
    value: null
train_sampling_strategy:
    value: random
transformers_version:
    value: 5.7.0
use_cache:
    value: false
use_cpu:
    value: false
use_liger_kernel:
    value: false
use_weighted_layer_sum:
    value: false
vocab_size:
    value: 49
warmup_ratio:
    value: null
warmup_steps:
    value: 0
weight_decay:
    value: 0.01
xvector_output_dim:
    value: 512
